spring.application.name=RestDemo
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=pass
# not in production
spring.jpa.hibernate.ddl-auto=update
# this is used in production
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto = none
#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql=true
